### ISSUE TITLE
[FEATURE] View Node temperature

### ISSUE THREAD

**Issue by HarshitBhatt043** [rcourtman/Pulse#101]
**Describe the solution you'd like**
Users can install lm-sensors on their nodes and check their node temp using sensors command , it would be beneficial if we can get the highest temp or Package id 0 temp in the web ui.
Below is an output of sensors command
`Adapter: Virtual device
temp1:        +26.0°C  
temp2:        +35.0°C  
temp3:        +29.0°C  
temp4:        +29.0°C  
temp5:        +32.0°C  
temp6:        +30.0°C  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +16.8°C  
temp2:        +16.8°C  
temp3:        +27.8°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +30.0°C  (high = +84.0°C, crit = +100.0°C)
Core 0:        +28.0°C  (high = +84.0°C, crit = +100.0°C)
Core 1:        +28.0°C  (high = +84.0°C, crit = +100.0°C)
Core 2:        +31.0°C  (high = +84.0°C, crit = +100.0°C)
Core 3:        +26.0°C  (high = +84.0°C, crit = +100.0°C)
Core 4:        +27.0°C  (high = +84.0°C, crit = +100.0°C)
Core 5:        +26.0°C  (high = +84.0°C, crit = +100.0°C)

nvme-pci-0400
Adapter: PCI adapter
Composite:    +31.9°C  (low  =  -0.1°C, high = +69.8°C)
                       (crit = +84.8°C)
Sensor 1:     +49.9°C  (low  =  +0.0°C, high =  +0.0°C)`
We can also get nvme temps if we want.

**Describe alternatives you've considered**
i have tried https://github.com/henrygd/beszel , but its using agents to get all the info, same with others like netdata.

**Comment by rcourtman** [comment]
Hi @HarshitBhatt043,

Thanks for the feature request\! Temperature monitoring is definitely something I've heard requested from multiple users, so it's on my radar.

It's not on my immediate to-do list, but I will look into implementing this in the near future. I'll need to research the best way to retrieve temperature data from Proxmox nodes reliably.

I'll update this issue when I start working on it.

**Comment by martusi61** [comment]
I agree about the importance of temperature values to monitor, this feature would make the package very complete. Thanks for the work done now.

**Comment by rcourtman** [comment]
Closing as stale. This feature request is from 6+ months ago. Feel free to reopen if you still want node temperature monitoring added to v4.

**Comment by rcourtman** [comment]
Reopening

**Comment by krom** [comment]
Proxmox does not provide this functionality in its basic form, but there [is a project](https://github.com/Meliox/PVE-mods) that allows you to display additional information in the web interface. Please take a look, maybe you can reuse it. I'm not sure that data is added to the REST API, but maybe it's worth taking as a basis. Otherwise, you will need to install additional software on the server.

<img width="1021" height="466" alt="Image" src="https://github.com/user-attachments/assets/0e82ae9b-84ab-4196-83c8-59dc593eba4e" />

**Comment by kenrmayfield** [comment]
@rcourtman 
@krom 

That Project for PVE-MODs(https://github.com/Meliox/PVE-mods) is a Excellent Repository.

I suggest it All the Time to Users whom want that Information in the Proxmox DashBoard.

Like krom stated.............the User will have to Install the Repo on their End as a PreRequisite and Pulse can Pull the Temperature and Fan Speed Data through REST API or maybe there is Another Method to Pull the Temperature Data and Fan Speed Data without Installing the PVE-MODs Repo by Strictly using Code Directly in Pulse that Directly accesses lm-sensors.

**Comment by rcourtman** [comment]
thanks for the discussion everyone. i've been thinking about this and here's my take:

modifying proxmox with pve-mods isn't sustainable - it breaks on updates and requires users to hack their systems. not ideal.

i'm considering a simpler approach:
1. use the existing api credentials to ssh into nodes
2. run `sensors -j` or read `/sys/class/thermal/` directly  
3. parse and display the temps in pulse

this would work with stock proxmox, no modifications needed. if sensors aren't installed or available, we just don't show temps for that node.

would this work for everyone's use case? main requirement would be that the pulse user has ssh access (which the auto-setup script could configure).

thoughts?

**Comment by rcourtman** [comment]
for those not familiar with the auto-setup script (it's a newer feature):

**how it works:**
1. go to Settings → Nodes in pulse
2. click "Setup Script" next to any discovered node
3. pulse generates a one-liner bash script
4. run it on your proxmox node (as root)

**what the script does:**
- creates a dedicated user (pulse-monitor@pam) 
- assigns minimal required permissions (PVEAuditor role)
- generates an api token for that user
- registers the token with pulse automatically
- optionally enables ssh for the pulse-monitor user (for features like temperature monitoring)

**security:**
- the pulse-monitor user has READ-ONLY permissions
- can't modify vms, containers, or settings
- can't access vm consoles or data
- only gets monitoring metrics
- ssh access (if enabled) is restricted to the pulse-monitor user, not root

**why this matters for temperature monitoring:**
if we implement temp monitoring via ssh, the auto-setup script could handle configuring ssh access for the pulse-monitor user automatically. no manual ssh key setup needed.

the script is transparent - you can read it before running. it's basically automating what you'd do manually but with consistent security settings.

**Comment by kenrmayfield** [comment]
@rcourtman 

**Your Comment..........................**
modifying proxmox with pve-mods isn't sustainable - it breaks on updates and requires users to hack their systems. not ideal.
..................................

Technically Yes on Updates to Proxmox you would have to Reinstall.   The PVE-MODs Script Inserts Code into pvemanager.js and nodes.pm Files. **The Original Files get Backed Up by the Script.**

**Comment by tim-rex** [comment]
Personally, I don't _love_ the idea of allowing/requiring direct ssh into any PVE nodes..  Ideally we would petition upstream Proxmox to expose `sensors -j` or `/sys/class/thermal` directly via their API though I appreciate that might be a non-starter

**Comment by kenrmayfield** [comment]
@rcourtman 

 lm-senors needs to be Installed............right?

**Comment by rcourtman** [comment]
Thanks for flagging it - I'm also not thrilled about needing SSH just to pull temperature data. Right now Pulse only uses key-based auth to run a single `sensors -j` and disconnects immediately, and I document how to lock that key down to that exact command with all forwarding disabled so it cannot be reused for anything else. If Proxmox ever surfaces the sensor data through their API I will switch over straight away; until then SSH is the only reliable source I have.

**Comment by rcourtman** [comment]
Yep, Pulse needs `lm-sensors` (plus a quick `sensors-detect --auto`) on each node so the `sensors -j` call has data to return. The node setup script will install it automatically if you answer "y" to the temperature prompt, otherwise the manual steps in docs/TEMPERATURE_MONITORING.md cover installing it yourself.

**Comment by kenrmayfield** [comment]
@rcourtman 

So for the Forwarding Restriction and to Force the SSH Key only for **sensors -j** you just Add the Line below:

**command="sensors -j",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2E...**

to the File **/root/.ssh/authorized_keys** which also contains the SSH Key.

**Comment by krom** [comment]
@rcourtman could you please help me with enabling temperature monitoring

I use version [4.21.0](https://github.com/rcourtman/Pulse/releases)

My Docker compose is
```
services:
  pulse-server:
    image: rcourtman/pulse:${TAG:-latest}
    container_name: pulse
    restart: unless-stopped
    env_file:
      - secrets/pulse.env
    ports:
      - "7655:7655"
    volumes:
      - ./data:/data
      - ./ssh:/home/pulse/.ssh
```
checking inside docker container
```
pulse:/srv/pulse# docker compose exec pulse-server sh
/app # apk add openssh-client
OK: 12 MiB in 25 packages
/app # su pulse
/app $ ssh root@pve-02.lan 'sensors -j'
{"amdgpu-pci-0500":{"Adapter":"PCI adapter","vddgfx":{"in0_input":1.300000},"vddnb":{"in1_input":0.793000},"edge":{"temp1_input":70.000000},"PPT":{"power1_input":25.000000},"sclk":{"freq1_input":400000000.000000}},"nvme-pci-0100":{"Adapter":"PCI adapter","Composite":{"temp1_input":48.850000,"temp1_max":89.850000,"temp1_min":-273.150000,"temp1_crit":94.850000,"temp1_alarm":0.000000},"Sensor 1":{"temp2_input":48.850000,"temp2_max":65261.850000,"temp2_min":-273.150000},"Sensor 2":{"temp3_input":66.850000,"temp3_max":65261.850000,"temp3_min":-273.150000}},"k10temp-pci-00c3":{"Adapter":"PCI adapter","Tctl":{"temp1_input":76.250000}}}
/app $ 
```

<img width="1343" height="288" alt="Image" src="https://github.com/user-attachments/assets/7d81eaa5-e64b-4f7e-a63f-b3a02da044ee" />

FYI: I configured my pulse instance manually many versions ago

**Comment by Freak-On-Silicon** [comment]
I installed Pulse today, really great software! Thanks for that.
But temp doesnt show up on the dashboard.

I have a 3node cluster. 
i installed the setup script on my first node, and all worls like a charm except the temps.

i installed Pulse in an lxc with the proxmox-helper-scripts.

sensors -j works an all 3 nodes, i also command sensors-detect --auto.
I rebootet all

**Comment by Freak-On-Silicon** [comment]
yes.

Mit freundlichen Grüßen
Lukas Sagl


Am Di., 7. Okt. 2025 um 10:28 Uhr schrieb kenrmayfield <
***@***.***>:

**Comment by LightTemplar** [comment]
Same problem here, temperature is not showing.

```
pulse@pulse-server:~$ ssh root@pve2.some.domain "sensors -j"
{"drivetemp-scsi-0-0":{"Adapter":"SCSI adapter","temp1":{"temp1_input":43.000000,"temp1_max":70.000000,"temp1_min":0.000000,"temp1_crit":70.000000,"temp1_lcrit":0.000000,"temp1_highest":51.000000}},"acpitz-acpi-0":{"Adapter":"ACPI interface","temp1":{"temp1_input":27.800000},"temp2":{"temp2_input":29.800000}},"coretemp-isa-0000":{"Adapter":"ISA adapter","Package id 0":{"temp1_input":50.000000,"temp1_max":84.000000,"temp1_crit":100.000000,"temp1_crit_alarm":0.000000},"Core 0":{"temp2_input":45.000000,"temp2_max":84.000000,"temp2_crit":100.000000,"temp2_crit_alarm":0.000000},"Core 1":{"temp3_input":47.000000,"temp3_max":84.000000,"temp3_crit":100.000000,"temp3_crit_alarm":0.000000},"Core 2":{"temp4_input":50.000000,"temp4_max":84.000000,"temp4_crit":100.000000,"temp4_crit_alarm":0.000000},"Core 3":{"temp5_input":45.000000,"temp5_max":84.000000,"temp5_crit":100.000000,"temp5_crit_alarm":0.000000}}}
```

and `journalctl -u pulse -f | grep -i temp` shows nothing about temperature, only records with my cluster name - it has "temp" letters in it.

Pulse v4.21.0, installed in LXC container with Debian 13 on Proxmox 9.0 node.

**Comment by dguerri** [comment]
Hi, I posted to the pve-dev ML patches to support reading sensors via API.

https://lists.proxmox.com/pipermail/pve-devel/2025-October/075850.html

I need some help testing the patches extensively (and maybe to "vote" pushing the PR upstream).

API hierarchy:
/sensors/temperature/ - Temperature sensors category
/sensors/temperature/cpu/ - CPU temperature sensors
/sensors/temperature/cpu/sensors - List CPU temperature sensor devices
/sensors/temperature/cpu/values - Read CPU temperature values
/sensors/temperature/disk/ - Disk temperature sensors
/sensors/temperature/disk/sensors - List disk temperature sensor devices
/sensors/temperature/disk/values - Read disk temperature values
/sensors/temperature/other/ - Other temperature sensors
/sensors/temperature/other/sensors - List other temperature sensor devices
/sensors/temperature/other/values - Read other temperature values
/sensors/fan/ - Fan sensors
/sensors/fan/sensors - List fan sensor devices
/sensors/fan/speeds - Read fan speeds

**Comment by rcourtman** [comment]
This should now be fixed in the latest commit. The issue was twofold:

1. **Hostname resolution**: Temperature collection was using the short node name (e.g., "pve2") instead of the actual hostname/FQDN from your config. Now it uses:
   - For cluster nodes: The IP from ClusterEndpoints
   - For standalone nodes: The Host URL from config (which includes your FQDN)
   - Fallback: Node name (for simple setups)

2. **SSH warnings**: The `sensors -j` output was being contaminated by SSH warnings like "Warning: Permanently added...", causing JSON parsing to fail. Fixed by separating stdout from stderr.

**To verify it's working:**
```bash
journalctl -u pulse-backend -f | grep -i temp
```

You should see `Collected temperature data` messages. If you see failures, check that:
- SSH keys are set up for passwordless root login to your nodes
- `lm-sensors` is installed on the nodes (`apt install lm-sensors && sensors-detect`)

Let me know if temperatures are now showing up in the UI!

**Comment by LightTemplar** [comment]
[rcourtman](https://github.com/rcourtman), could you please release new version with these fixes?

**Comment by rcourtman** [comment]
they'll be an rc release shortly

**Comment by LightTemplar** [comment]
It's working in the v4.22.0-rc.1, the temperature is here!

**Comment by Knallebal** [comment]
i've just set up a pulse lxc, everything is working, but my proxmox nodetemperature  displays:  0 degrees Celcius
is that a bug, or did i misconfigure something?

**Comment by rcourtman** [comment]
v4.23.0 includes improved NVMe temperature detection to prevent false readings. Can you try the new release?

**Comment by Knallebal** [comment]
i updated to 4.23.0    now it says:  no CPU sensor

**Comment by krom** [comment]
@rcourtman I use docker and have read [the manual Secure Architecture v4.24.0+](https://github.com/rcourtman/Pulse/blob/main/docs/TEMPERATURE_MONITORING.md#secure-architecture-v4240)

Could you please provide manual installation steps of pulse-sensor-proxy because I use ansible for PVE Node provisioning

**Comment by krom** [comment]
> [@rcourtman](https://github.com/rcourtman) I use docker and have read [the manual Secure Architecture v4.24.0+](https://github.com/rcourtman/Pulse/blob/main/docs/TEMPERATURE_MONITORING.md#secure-architecture-v4240)
> 
> Could you please provide manual installation steps of pulse-sensor-proxy because I use ansible for PVE Node provisioning

I've prepared basic ansible role based on installation script https://github.com/rcourtman/Pulse/issues/546

**Comment by rcourtman** [comment]
Manual host-side install steps for `pulse-sensor-proxy` are now documented at https://github.com/rcourtman/Pulse/blob/main/docs/TEMPERATURE_MONITORING.md#manual-installation-host-side. The section mirrors what the helper script does—download the release binary, create the service user/directories, drop in the hardened systemd unit, enable it, and bind-mount /run/pulse-sensor-proxy into the container—so it should translate cleanly into your Ansible role.

**Comment by krom** [comment]
I configured it
```
pulse:/srv/pulse# docker compose exec pulse-server ls -lh /run/pulse-sensor-proxy
total 0      
srw-rw-rw-    1 nobody   nobody         0 Oct 13 23:02 pulse-sensor-proxy.sock
```

```
pulse:/srv/pulse# docker compose logs pulse-server | grep proxy
pulse  | 11:04PM INF Temperature proxy detected - using secure host-side bridge
pulse  | 11:07PM INF Temperature proxy detected - using secure host-side bridge
pulse  | 11:07PM INF Temperature proxy detected - using secure host-side bridge
pulse  | 11:08PM INF Temperature proxy detected - using secure host-side bridge
pulse  | 11:10PM INF Temperature proxy detected - using secure host-side bridge
pulse  | 11:11PM INF Temperature proxy detected - using secure host-side bridge
pulse  | 11:11PM INF Temperature proxy detected - using secure host-side bridge
pulse  | 11:11PM INF Temperature proxy detected - using secure host-side bridge
pulse  | 11:12PM INF Temperature proxy detected - using secure host-side bridge
pulse  | 11:14PM INF Temperature proxy detected - using secure host-side bridge
```
```
root@pve-02:~# systemctl status  pulse-sensor-proxy.service 
● pulse-sensor-proxy.service - Pulse Temperature Proxy
     Loaded: loaded (/etc/systemd/system/pulse-sensor-proxy.service; disabled; preset: enabled)
     Active: active (running) since Tue 2025-10-14 02:02:51 MSK; 14min ago
 Invocation: 178b851baa5f412497f5d43ffb96e3dc
       Docs: https://github.com/rcourtman/Pulse
   Main PID: 581716 (pulse-sensor-pr)
      Tasks: 9 (limit: 74457)
     Memory: 4.2M (peak: 4.8M)
        CPU: 215ms
     CGroup: /system.slice/pulse-sensor-proxy.service
             └─581716 /usr/local/bin/pulse-sensor-proxy

окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM DBG Peer credentials gid=101000 pid=700332 uid=101000
окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM WRN Peer credentials unavailable error="unauthorized: uid=101000 gid=101000"
окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM DBG Peer credentials gid=101000 pid=700332 uid=101000
окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM WRN Peer credentials unavailable error="unauthorized: uid=101000 gid=101000"
окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM DBG Peer credentials gid=101000 pid=700332 uid=101000
окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM WRN Peer credentials unavailable error="unauthorized: uid=101000 gid=101000"
окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM DBG Peer credentials gid=101000 pid=700332 uid=101000
окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM WRN Peer credentials unavailable error="unauthorized: uid=101000 gid=101000"
окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM DBG Peer credentials gid=101000 pid=700332 uid=101000
окт 14 02:17:11 pve-02 pulse-sensor-proxy[581716]: 2:17AM WRN Peer credentials unavailable error="unauthorized: uid=101000 gid=101000"

```
But see no temperature
<img width="1478" height="289" alt="Image" src="https://github.com/user-attachments/assets/d09fab51-2124-4e91-b6c9-2d968bbc269f" />

Looks like problem with LXC uid:gid mapping

**Comment by rcourtman** [comment]
Thanks for the detailed logs and screenshots. The proxy UID/GID fix is merged for the upcoming 4.24 build (`cmd/pulse-sensor-proxy/auth.go:70`), so once that release lands the container bridge should authenticate cleanly and temperatures will start flowing. While preparing for that update, note the recent authentication changes: Pulse now manages multiple API tokens instead of a single shared value (`internal/api/security_tokens.go:35`, `internal/config/api_tokens.go:183`). The Settings → Security screen surfaces the new manager (`frontend-modern/src/components/Settings/APITokenManager.tsx:35`), and automation can drive it via the JSON endpoints (`GET/POST /api/security/tokens`, `DELETE /api/security/tokens/{id}`). Existing env vars still pick up the newest token for compatibility, but issuing one token per host will make future revocations simpler.

**Comment by KrOnAsK** [comment]
I just tried the new install script and it asked me if I wanted to enable temperature monitoring and I pressed yes, then it told me it found the lm-sensors package and everything worked correctly  but I still dont see my temps in pulse: 

<img width="1908" height="1134" alt="Image" src="https://github.com/user-attachments/assets/1e0d6786-a563-4e38-8890-029c13eca39d" />

**Comment by hamid-elaosta** [comment]
Hi,

I just installed 4.24 and was unable to get temperature working, but having read the architecture docs it seems my deployment isn't "typical".

I'm running Pulse in a Podman container on a separate machine running Alpine (on ARM64), auto-configured the Proxmox node from the Pulse UI with the one-liner and already had lm-sensors installed and configured on the Proxmox host, but the temperature column doesn't show up in Pulse.

From the docs it appears that the intention is for the proxy to run on the host Pulse runs on so that it can SSH into the Proxmox node, then bind mount the proxy into the Pulse container so it has access to the socket.

Does that mean I should manually install the proxy on the Alpine/ARM box and bind mount it to Pulse and run the setup again? No SSH authorized_keys have been created for my root user on the Proxmox host yet, after going through the interactive configuration and saying yes to the temperature setup, so I assume that happens after the proxy is available?

EDIT: Got the proxy installed on my Alpine host and bind mounted to pulse but I see an error in the proxy log.
```
1:24AM DBG Peer credentials gid=1000 pid=27405 uid=1000
1:24AM WRN Peer authorization failed error="unauthorized: uid=1000 gid=1000" gid=1000 uid=1000
```
I'm not clear what it means by "Peer authorization failed". The listed UID and GID match my own user both on the Alpine box and the Proxmox node, and not the user the proxy is running as, ~~nor the user Podman is running as on the Alpine box~~ the pulse pod is running as my user also;

I'm not sure if the proxy is trying to ssh as my user, so I've added my user's public key from Pulse host to my own user's authorized keys on Proxmox but the error persists.

EDIT2: I've managed to get a little further; by adding the SSH key from /var/lib/pulse-sensor-proxy to the root user's authorized keys on Proxmox and setting my user's uid/gid in the proxy config, I now get a partial success, but an RPC error:
```
2:11AM DBG Peer credentials gid=1000 pid=31349 uid=1000
2:11AM INF Temperature data fetched successfully corr_id=3d3f80e1-db06-45e7-8cb9-ad523118fc10 method=get_temperature node=192.168.1.199 pid=31349 uid=1000
2:11AM INF Request completed corr_id=3d3f80e1-db06-45e7-8cb9-ad523118fc10 method=get_temperature pid=31349 uid=1000
2:11AM ERR Failed to encode RPC response error="write unix /run/pulse-sensor-proxy/pulse-sensor-proxy.sock->@: write: broken pipe"
```
EDIT3: Recompiled the pulse-sensor-proxy with a debug log at the RPC error, the issue is that the returned data contains non-JSON text:
```
DBG map[node:192.168.1.199 temperature:Pseudo-terminal will not be allocated because stdin is not a terminal.
{"k10temp-pci-00c3":{"Adapter":"PCI adapter","Tctl":{"temp1_input":49.500000},"Tccd1":{"temp3_input":50.750000},"Tccd2"...
```

Adding `-T` to the SSH command in the proxy stopped the pseudo-terminal text message, but it did not resolve the broken pipe, I'm going to call it a night there.
```
diff --git a/cmd/pulse-sensor-proxy/ssh.go b/cmd/pulse-sensor-proxy/ssh.go
index 69bbdf3..8c794bd 100644
--- a/cmd/pulse-sensor-proxy/ssh.go
+++ b/cmd/pulse-sensor-proxy/ssh.go
@@ -136,7 +136,7 @@ func (p *Proxy) testSSHConnection(nodeHost string) error {
 
        privKeyPath := filepath.Join(p.sshKeyPath, "id_ed25519")
        cmd := fmt.Sprintf(
-               `ssh -i %s -o StrictHostKeyChecking=no -o ConnectTimeout=5 root@%s "echo test"`,
+               `ssh -T -i %s -o StrictHostKeyChecking=no -o ConnectTimeout=5 root@%s "echo test"`,
                privKeyPath,
                nodeHost,
        )
@@ -166,7 +166,7 @@ func (p *Proxy) getTemperatureViaSSH(nodeHost string) (string, error) {
        // Since we use ForceCommand="sensors -j", any SSH command will run sensors
        // We don't need to specify the command
        cmd := fmt.Sprintf(
-               `ssh -i %s -o StrictHostKeyChecking=no -o ConnectTimeout=5 root@%s ""`,
+               `ssh -T -i %s -o StrictHostKeyChecking=no -o ConnectTimeout=5 root@%s ""`,
                privKeyPath,
                nodeHost,
        )
```
Complete `sensors -j` output from `resp.Data` as logged in the proxy with my debug log:
```json
{ "k10temp-pci-00c3":{"Adapter":"PCI adapter","Tctl":{"temp1_input":50.750000},"Tccd1":{"temp3_input":53.000000},"Tccd2":{"temp4_input":49.000000}},"nvme-pci-2600":{"Adapter":"PCI adapter","Composite":{"temp1_input":46.850000,"temp1_max":84.850000,"temp1_min":-273.150000,"temp1_crit":84.850000,"temp1_alarm":0.000000},"Sensor 1":{"temp2_input":46.850000,"temp2_max":65261.850000,"temp2_min":-273.150000},"Sensor 2":{"temp3_input":51.850000,"temp3_max":65261.850000,"temp3_min":-273.150000}},"nct6779-isa-0290":{"Adapter":"ISA adapter","Vcore":{"in0_input":0.496000,"in0_min":0.000000,"in0_max":1.744000,"in0_alarm":0.000000,"in0_beep":0.000000},"in1":{"in1_input":1.264000,"in1_min":0.000000,"in1_max":0.000000,"in1_alarm":1.000000,"in1_beep":0.000000},"AVCC":{"in2_input":3.376000,"in2_min":2.976000,"in2_max":3.632000,"in2_alarm":0.000000,"in2_beep":0.000000},"+3.3V":{"in3_input":3.376000,"in3_min":2.976000,"in3_max":3.632000,"in3_alarm":0.000000,"in3_beep":0.000000},"in4":{"in4_input":1.832000,"in4_min":0.000000,"in4_max":0.000000,"in4_alarm":1.000000,"in4_beep":0.000000},"in5":{"in5_input":1.048000,"in5_min":0.000000,"in5_max":0.000000,"in5_alarm":1.000000,"in5_beep":0.000000},"in6":{"in6_input":1.192000,"in6_min":0.000000,"in6_max":0.000000,"in6_alarm":1.000000,"in6_beep":0.000000},"3VSB":{"in7_input":3.376000,"in7_min":2.976000,"in7_max":3.632000,"in7_alarm":0.000000,"in7_beep":0.000000},"Vbat":{"in8_input":3.216000,"in8_min":2.704000,"in8_max":3.632000,"in8_alarm":0.000000,"in8_beep":0.000000},"in9":{"in9_input":0.000000,"in9_min":0.000000,"in9_max":0.000000,"in9_alarm":0.000000,"in9_beep":0.000000},"in10":{"in10_input":0.936000,"in10_min":0.000000,"in10_max":0.000000,"in10_alarm":1.000000,"in10_beep":0.000000},"in11":{"in11_input":1.032000,"in11_min":0.000000,"in11_max":0.000000,"in11_alarm":1.000000,"in11_beep":0.000000},"in12":{"in12_input":1.696000,"in12_min":0.000000,"in12_max":0.000000,"in12_alarm":1.000000,"in12_beep":0.000000},"in13":{"in13_input":0.960000,"in13_min":0.000000,"in13_max":0.000000,"in13_alarm":1.000000,"in13_beep":0.000000},"in14":{"in14_input":1.856000,"in14_min":0.000000,"in14_max":0.000000,"in14_alarm":1.000000,"in14_beep":0.000000},"fan1":{"fan1_input":0.000000,"fan1_min":0.000000,"fan1_alarm":0.000000,"fan1_beep":0.000000,"fan1_pulses":2.000000},"fan2":{"fan2_input":0.000000,"fan2_min":0.000000,"fan2_alarm":0.000000,"fan2_beep":0.000000,"fan2_pulses":2.000000},"fan3":{"fan3_input":0.000000,"fan3_min":0.000000,"fan3_alarm":0.000000,"fan3_beep":0.000000,"fan3_pulses":2.000000},"fan4":{"fan4_input":0.000000,"fan4_min":0.000000,"fan4_alarm":0.000000,"fan4_beep":0.000000,"fan4_pulses":2.000000},"fan5":{"fan5_input":0.000000,"fan5_min":0.000000,"fan5_alarm":0.000000,"fan5_beep":0.000000,"fan5_pulses":2.000000},"SYSTIN":{"temp1_input":34.000000,"temp1_max":0.000000,"temp1_max_hyst":0.000000,"temp1_alarm":1.000000,"temp1_type":4.000000,"temp1_offset":0.000000,"temp1_beep":0.000000},"CPUTIN":{"temp2_input":42.500000,"temp2_max":80.000000,"temp2_max_hyst":75.000000,"temp2_alarm":0.000000,"temp2_type":4.000000,"temp2_offset":0.000000,"temp2_beep":0.000000},"AUXTIN0":{"temp3_input":15.500000,"temp3_type":4.000000,"temp3_offset":0.000000},"AUXTIN1":{"temp4_input":29.000000,"temp4_type":4.000000,"temp4_offset":0.000000},"AUXTIN2":{"temp5_input":24.000000,"temp5_type":4.000000,"temp5_offset":0.000000},"AUXTIN3":{"temp6_input":-29.000000,"temp6_type":4.000000,"temp6_offset":0.000000},"PCH_CHIP_CPU_MAX_TEMP":{"temp7_input":0.000000},"PCH_CHIP_TEMP":{"temp8_input":0.000000},"PCH_CPU_TEMP":{"temp9_input":0.000000},"PCH_MCH_TEMP":{"temp10_input":0.000000},"PCH_DIM0_TEMP":{"temp11_input":0.000000},"PCH_DIM1_TEMP":{"temp12_input":0.000000},"TSI0_TEMP":{"temp13_input":50.375000},"pwm1":{"pwm1":127.500000,"pwm1_enable":0.000000,"pwm1_mode":1.000000},"pwm2":{"pwm2":127.500000,"pwm2_enable":0.000000,"pwm2_mode":1.000000},"pwm3":{"pwm3":127.500000,"pwm3_enable":0.000000,"pwm3_mode":1.000000},"pwm4":{"pwm4":127.500000,"pwm4_enable":0.000000,"pwm4_mode":1.000000},"pwm5":{"pwm5":127.500000,"pwm5_enable":0.000000,"pwm5_mode":1.000000},"intrusion0":{"intrusion0_alarm":1.000000,"intrusion0_beep":0.000000},"intrusion1":{"intrusion1_alarm":1.000000,"intrusion1_beep":0.000000},"beep_enable":{"beep_enable":0.000000}}}
```

**Comment by rcourtman** [comment]
I tested the proxy change on 4.24 with lm-sensors and could not reproduce the broken pipe as long as the SSH user has ForceCommand set to run sensors without banners. The extra `Pseudo-terminal will not be allocated...` line comes from the remote shell and indicates the proxy is not running against a clean command-only session. I do not have a clear way to act on this from the Pulse side, so I am going to close this out. Please reopen if this is still relevant.

**Comment by rcourtman** [comment]
I'm closing this out since the proxy works as long as the SSH user runs sensors without extra shell banners through ForceCommand. Please reopen if this is still relevant.

**Comment by rcourtman** [comment]
I cannot reproduce this when the SSH user is restricted to run sensors via ForceCommand without extra shell output. The pseudo-terminal banner points to a remote shell configuration issue that Pulse cannot address. Please reopen if this is still relevant.

**Comment by rcourtman** [comment]
I am closing this because the proxy works when sensors is run through ForceCommand without extra shell output, so there is no actionable change on the Pulse side. Please reopen if this is still relevant.

**Comment by martusi61** [comment]
Great work, "Pulse" is on its way to becoming a system standard. However, the temperature display still doesn't work for me. I followed the instructions, on my PVE1 I ran the script as per Pulse settings, it doesn't display any errors, but after doing some checks I noticed that pulse-sensor-proxi is not installed that's why the temperature display is missing. LM-Sensors exist. I remain available for any log requests. Also, looking quickly at the complex script, I also noticed that a condition check is done with the "running" of the docker container, but mine only shows "healthy".

Pulse 4.24.0-rc.3 version running in LXC with Docker container on PVE1
PVE1 and PVE2 are running on version 9
QDevice running in Armbian OS
