### ISSUE TITLE
4.x is not ready for production and needs to have several issues resolved before leaving 3.x for use

### ISSUE THREAD

**Issue by da99Beast** [rcourtman/Pulse#272]
I am having issues with the 4.x line of Pulse.

I use only Discord for notifications but it will not save. It says it is saved but when I move away and come back, it is not there.  The email will save (even when I only slide the enable slider but don't put in any valid data).

The storage area in 3.x would show local and shared per node.  The 4.x shows shared above the nodes.  This would be ok but doesn't show what node has what share mounted.  It also shows duplicates (if the same share is on multiple nodes).  The 3.x presentation makes more sense.

on 4.x the backup type is always LXC but I have a mix of both LXC and VM backups.  3.x shows this properly.

I backup my pve configs using pbs and those don't show up in 4.x at all but do show up in 3.x as expected.

I think you need to slow down your 4.x line and fix it so things actually work - or at least get it to the same state of functionality as version 3.42.0 has.

I used your 4.x docker compose example to test with the 4.x line as I had issues initially and I wanted to rule out issues on my config before opening up this issue for you to track.

Let me know if you would like screen shots showing these issues.

**Comment by da99Beast** [comment]
Feedback on the v4.1.0-rc.5 with the above and more issues....

It did resolve the saving of the Discord webhook - however it doesn't appear to actually work.  The test states it sent a test for the webhook but it didn't post anything on Discord.  This is the same URL for Discord that the 3.x instance is using so I know it is working.

Backup types are now all VM and none are LXC.  I have a mix so I should see a mix.  My PVE config backups still don't show.

Storage is same issue.  Shared section shows duplicates and doesn't show what node(s) are connected to what shared storage.

I used the 4.x docker compose with the version hard coded to the rc.5 and removed the data volume in docker before setting up the system manually again (no export/import so I didn't import a bad config).

New thing I noticed in this version is any alerts that are present can't be acknowledged.  A pop up in the upper right says "failed to acknowledge alert".  The other issue is the clear alert doesn't just clear the 1 alert item, it clears them all.  Another thing is it doesn't appear to take my alert thresholds into consideration and continues to use the defaults.

**Comment by wisepds** [comment]
For me it's a nightmare... nothing work... i configured pbs and dissapear! I don't know what's happen, but i think it's more important to go step by step with low number of funtionalities, but working 100%.

**Comment by da99Beast** [comment]
As I continue to test new releases.... 4.1.4 is not available at this time for docker so testing 4.1.3.

Most things appear to be resolved from above.  Some comments on the backups view...

The Name and the Details fields appear to be the same and are pulled from the comment of the backup.  I think the Name field should be pulled from the backup group (as looking at the backup volume contents in PBS).  The Details are good with the comments from the PBS backup.

The Storage view still shows the shared storage outside of the host it is mounted on but doesn't show what host(s) have it mounted.  Also still shows duplicates.

I found upgrading from the RC previously used to the 4.1.3 my config was messed up - alerts were present showing systems but no PVE or PBS were setup.  I deleted the data vol in docker again and setup the system again and tried to export the config - error on export.  

Alerts still can't ack them and clear still clears all and they come back.  Looks like the triggers are still using the default instead of what I set in the thresholds.

**Comment by da99Beast** [comment]
Now that 4.1.5 is available for docker I am trying again.  

Upgrade from 4.1.3 to 4.1.5 still breaks the config - no PVE or PBS configured.  Wiped and started again.

This time I am looking only at the export/import aspect.  I still get the error.

I tried to setup the API_TOKEN in docker compose but it didn't like it.  I stopped that and ran docker command line instead (not -d option) and the API_TOKEN worked.

Issue is the export is still blocked.

I tried with the "ALLOW_UNPROTECTED_EXPORT=TRUE" instead of the API_TOKEN and it still is blocked.

with the API_TOKEN set I get this in the log:

```
6:12PM WRN Unauthorized API access attempt ip=192.168.5.223:60715 path=/api/tokens/list
6:12PM DBG Request handled duration=0.410594 method=GET path=/api/tokens/list
6:12PM WRN Request failed method=GET path=/api/tokens/list request_id=1754849558827002597 status=401

6:12PM WRN Unauthorized export attempt ip=192.168.5.223:60715 path=/api/config/export
6:12PM DBG Request handled duration=0.129375 method=POST path=/api/config/export
6:12PM WRN Request failed method=POST path=/api/config/export request_id=1754849570747296804 status=401
```


with the ALLOW_UNPROTECTED_EXPORT set I get this in the log:
```
6:14PM WRN Export blocked - API token required ip=192.168.5.223:60801
6:14PM DBG Request handled duration=0.172681 method=POST path=/api/config/export
6:14PM WRN Request failed method=POST path=/api/config/export request_id=1754849689895758961 status=403
```

**Comment by da99Beast** [comment]
I recently looked at the auto-discovery of the PVE/PBS but there is an issue when running in docker - it only looks at the docker generated subnet.  As you can see below in the logs, the docker subnet is 192.168.80.0/24 but my WebSocket shows a 192.168.5.0/24 network.

Can we have the ability to set what subnet(s) to scan for PVE/PBS systems?

```
2025-08-10T18:51:59.125606692Z 6:51PM INF Starting background discovery scan subnet=auto
2025-08-10T18:51:59.125693032Z 6:51PM INF Starting network discovery subnet=auto
2025-08-10T18:51:59.126052317Z 6:51PM INF Serving frontend from staticDir=/app/frontend-modern/dist
2025-08-10T18:51:59.127225500Z 6:51PM INF Server listening host=0.0.0.0 port=7655
2025-08-10T18:51:59.127297637Z 6:51PM INF Auto-detected local subnet detected=192.168.80.0/24
2025-08-10T18:51:59.127449618Z 6:51PM INF IPs to scan count=254
2025-08-10T18:51:59.435170661Z 6:51PM INF WebSocket upgrade request host=192.168.5.8:7654 origin=http://192.168.5.8:7654 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
```

As you

**Comment by rcourtman** [comment]
discord webhook avatar URLs fixed in upcoming release - was pointing to wrong repo

**Comment by rcourtman** [comment]
discord webhook avatar URLs fixed - will be in next release after v4.1.6

**Comment by da99Beast** [comment]
First I need to give props to @rcourtman as you are making updates on the fly to my posts.  Thank you.

Looks like in v4.1.6 I got the export to work now.  The environmental setting for "ALLOW_UNPROTECTED_EXPORT" works.

**Comment by da99Beast** [comment]
More props to @rcourtman for the "DISCOVERY_SUBNET" env setting.  I have validated this is working as expected.

I didn't realize in my testing you released the 4.1.7 that had this in it.  

I still have issues with the export when I use the API_TOKEN setting but I am not worried about it as it works with the other "ALLOW_UNPROTECTED_EXPORT" set.  I am only mentioning it as others may want to use it.

I will give it some time to settle down but most of my issues appear to have been resolved.

I will work on testing the alert thresholds - looks like some are applying properly now - may need some burn in time.

**Comment by da99Beast** [comment]
I am closing this now with all the work done to resolve the big issues.  Any issues I find now will be opened under a new issue.
