### ISSUE TITLE
Don't copy PVE config to PBS

### ISSUE THREAD

**Issue by krom** [rcourtman/Pulse#296]
When I add PVE on a clean system (I have a cluster, if that matters), then when I open the tab for adding PBS, some of the fields for connecting to PBS are filled with the settings for connecting to PVE, this is not entirely correct and not obvious behavior, it is worth leaving the PBS settings fields empty

**Comment by rcourtman** [comment]
hey @krom, fixed in v4.2.0 - PBS forms shouldn't get contaminated with PVE data anymore. can you test and confirm?

**Comment by RLSinRFV** [comment]
@rcourtman in v3.x, there was a separate tab for PBS instances that displayed a lot of very useful data.  This appears to be gone in v4.  Will this be added back?

**Comment by krom** [comment]
Pulse | Version: [4.2.0](https://github.com/rcourtman/Pulse/releases) - Docker
<img width="721" height="1317" alt="Image" src="https://github.com/user-attachments/assets/7b972e71-bac0-43d6-8790-15afb7bd6e81" />

Not fixed

**Comment by krom** [comment]
Another issue: when editing the PBS node, the form is not filled with data from the configuration

<img width="726" height="1295" alt="Image" src="https://github.com/user-attachments/assets/3a0671e1-238b-40fc-93ce-4823b05f076c" />

**Comment by rcourtman** [comment]
hey @krom, the PBS edit form issue should be fixed in v4.2.1 which just released. the form now correctly loads the token authentication data when editing PBS nodes. can you update and test?

**Comment by krom** [comment]
@rcourtman I checked. PBS editing works fine now. Thanks
