### ISSUE TITLE
Error when execute docker-agent-install script

### ISSUE THREAD

**Issue by markusglaetzner** [rcourtman/Pulse#528]
I execute the script and get "curl: (22) The requested URL returned error: 401"- I tried it on 2 different docker-hosts.

**Comment by rcourtman** [comment]
which version

**Comment by DrLabel** [comment]
same problem 
Pulse | Version: 4.22.0

**Comment by markusglaetzner** [comment]
Version: 4.22.0

**Comment by rcourtman** [comment]
@markusglaetzner @DrLabel Can you try rc5?

**Comment by markusglaetzner** [comment]
Yes, I will test it tomorrow, thanks.

**Comment by DrLabel** [comment]
I continue to have same error on Pulse | Version: [4.22.0-rc.5](https://github.com/rcourtman/Pulse/releases)

**Comment by rcourtman** [comment]
Thanks for the extra reports. The 401 ended up being caused by trailing slashes in the Pulse URL which produced a double `//download` path – that was fixed in v4.22.0-rc.5 (commit 5d077465a69b), and the installer now normalises the URL before downloading the agent.

Could you re-fetch the install script to make sure you get the updated copy? Some proxies/CDNs will cache the older script, so running something like:

```bash
curl -fsSL "https://<your-pulse-host>/install-docker-agent.sh?cachebust=$(date +%s)" \ 
  | bash -s -- --url https://<your-pulse-host> --token <api-token>
```

(or grabbing the script once and checking it contains `PULSE_URL="${PULSE_URL%/}"`) will confirm you have the new version. If you still hit a 401 after pulling the fresh script, please let us know the exact command you’re running and the value of `--url` (feel free to redact the hostname) so we can dig deeper.

**Comment by DrLabel** [comment]
curl -fsSL "http://192.168.1.86:7655/install-docker-agent.sh?cachebust=$(date +%s)"    | bash -s -- --url http://192.168.1.86:7655 --token ##########################################
curl: (22) The requested URL returned error: 404
now is error 404

**Comment by rsb-developer** [comment]
I'm also getting the 404 error.  I confirmed I have the latest version that normalizes PULSE_URL.  I added some debug output and these what is being requested.  Pulse is installed using the docker image if that makes any difference.

```
wget -q --show-progress -O /usr/local/bin/pulse-docker-agent http://pulse.home:7655/download/pulse-docker-agent?arch=linux-arm64
curl: (22) The requested URL returned error: 404

wget -q --show-progress -O /usr/local/bin/pulse-docker-agent http://pulse.home:7655/download/pulse-docker-agent
curl: (22) The requested URL returned error: 404
```

**Comment by rcourtman** [comment]
v4.23.0 includes improvements to the Docker agent installer script with better handling for BusyBox wget (Alpine Linux). Can you try the new release?

**Comment by rsb-developer** [comment]
I'm on the 4.23.0 release.  

I logged into the container and can see the pulse-docker-agent file.

```
/app # ls -l
total 20492
-rw-r--r--    1 pulse    pulse            7 Oct 12 09:37 VERSION
-rwxr-xr-x    1 pulse    pulse     14287032 Oct 12 09:43 pulse
-rwxr-xr-x    1 pulse    pulse      6684856 Oct 12 09:43 pulse-docker-agent
/app # cat VERSION
4.23.0
/app # 
```

Is only amd64 agent supported or is there a arm64 version as well?  I see the install script includes the architecture argument.

By the way, very nice project!  Thanks for the work.

**Comment by rcourtman** [comment]
Addressed in d74a6cc5c. The Docker image was only building the docker-agent for the host architecture. When users on ARM systems tried to download the agent, they received 404 errors because the ARM binaries did not exist at /opt/pulse/bin/ inside the container.

The Dockerfile now builds amd64, arm64, and armv7 binaries during the build process and includes all three in the final image. Tested that all architectures download correctly from a Docker deployment. This will be available in the next release.

**Comment by markusglaetzner** [comment]
Installed Version 4.23.0 a few minitues ago, tried to install the agent (on d Debian 12 Docker Host > amd64) and get "curl: (22) The requested URL returned error: 404"

**Comment by anyblabla** [comment]
Same here? Error 404 with Docker version 4.23.0 in a Debian 12 LXC :)

**Comment by markusglaetzner** [comment]
Closed?!? Does the installation work for anybody who wrote that it does not? I could not verify finctionality yet.

**Comment by rcourtman** [comment]
> Addressed in [d74a6cc](https://github.com/rcourtman/Pulse/commit/d74a6cc5cbfeaff0c0dd75f110cd90a3527992c3). The Docker image was only building the docker-agent for the host architecture. When users on ARM systems tried to download the agent, they received 404 errors because the ARM binaries did not exist at /opt/pulse/bin/ inside the container.
> 
> The Dockerfile now builds amd64, arm64, and armv7 binaries during the build process and includes all three in the final image. Tested that all architectures download correctly from a Docker deployment. This will be available in the next release.

It was fixed, I just havn't created a release yet since the fix

**Comment by markusglaetzner** [comment]
I  told you that I tried to nstall the agent an normal x86 system, not arm.

**Comment by rcourtman** [comment]
Reopening - I identified the actual root cause. The ARM fix (d74a6cc5c) was for a separate issue.

**Root cause:**
The v4.23.0 Docker image did not include the docker-agent binary at the path where the download endpoint searches for it. The router searches these paths in order:
1. `/opt/pulse/bin/pulse-docker-agent-linux-amd64` (when arch param provided)
2. `/opt/pulse/pulse-docker-agent-linux-amd64` (when arch param provided)
3. `/opt/pulse/bin/pulse-docker-agent` (fallback)
4. `/opt/pulse/pulse-docker-agent` (fallback)

In v4.23.0, none of these paths existed in the Docker image. The binary was copied to `/app/pulse-docker-agent` instead.

**Fix:**
Commit 64a63f80f adds all required binaries to `/opt/pulse/bin/`:
- `pulse-docker-agent-linux-amd64`
- `pulse-docker-agent-linux-arm64`
- `pulse-docker-agent-linux-armv7`
- `pulse-docker-agent` (fallback)

Verified locally - all four binaries now exist in the correct location.

This will be included in the next release. Once released, please rerun the installer and the 404 errors should be resolved.

**Comment by markusglaetzner** [comment]
Installation Docker-Agent with Version 4.24.0-rc.2: successfull :-) Thanks a lot for your great work. For me this is fine now. Very, very nice!

**Comment by markusglaetzner** [comment]
Unfortunately I have another issue with the pulse-docker-agent: after a few minutes the docker host is shown as offline in the UI, though the service in terminal is still shown as running. Restart service didn't work, restart host didn't work. Deinstallation and new installation worked, but only for a few minutes. The Containers are shown as running all the time.
Same problem with a second docker host.

<img width="1591" height="350" alt="Image" src="https://github.com/user-attachments/assets/96b53edf-a857-4ec1-8a83-aa9b3d0fb67f" />

Error in Terminal after "journalctl -u pulse-docker-agent -f" is:
Okt 13 20:44:30 docker01 pulse-docker-agent[5424]: {"level":"error","component":"pulse-docker-agent","error":"target https://pulse.mydonain.com: pulse responded with status 401 Unauthorized","time":"2025-10-13T20:44:30+02:00","message":"Failed to send docker report"}

**Comment by markusglaetzner** [comment]
Ok, after deinstallation on both docker host and new installation an both host with the same API Key, it seems to work. I thought the key is only for the install process. This meens the API Key has to be saved in a vault. Ok, now I have seen that the token is saved in the service, too. That's the reason why the first docker host is shown as offline a few minutes after I installed a second docker host with another API Key :-) Please make a big note in the install settings, that one API Key has to be used for all pulse-docker-agent installations. Now it seems to work fine.

**Comment by mr-pmillz** [comment]
@rcourtman 

Can you add support for installing the docker-agent on systems like Flatcar that have certain paths such as /usr set to read-only file systems?

Pulse Version: `v4.24.0-rc.2`

Here's the output from trying to run the script on Flatcar:

```shell
core@localhost ~ $  sudo curl -fsSL "https://REDACTED/install-docker-agent.sh?cachebust=$(date +%s)" | sudo bash -s -- --url https://REDACTED --token 'REDACTED'
===================================
Pulse Docker Agent Installer
===================================
Primary Pulse URL: https://REDACTED
Install path: /usr/local/bin/pulse-docker-agent
Interval: 30s
API token: (provided)
Targets:
  - https://REDACTED

Downloading Pulse Docker agent...
/usr/local/bin/pulse-docker-agent: Read-only file system
Warning: Failed to open the file /usr/local/bin/pulse-docker-agent: Read-only
Warning: file system
curl: (23) client returned ERROR on write of 15375 bytes

/usr/local/bin/pulse-docker-agent: Read-only file system
Warning: Failed to open the file /usr/local/bin/pulse-docker-agent: Read-only
Warning: file system
curl: (23) client returned ERROR on write of 15375 bytes

Error: Failed to download agent binary
Make sure the Pulse server is accessible at: https://REDACTED
```

**Comment by rcourtman** [comment]
Commit 483845330 updates the installer to fall back to a writable location when /usr/local/bin is read only, reuse existing agent locations, and provide an optional agent path override via PULSE_AGENT_PATH or the agent path CLI option. This will ship in the next release; please retry the install on Flatcar once it is available and report back if the read only error persists.

**Comment by mr-pmillz** [comment]
@rcourtman  That fixed it, thanks!
