### ISSUE TITLE
Webhook alerts still being sent for disabled metrics

### ISSUE THREAD

**Issue by revilo951** [rcourtman/Pulse#561]
**Describe the bug**
Webhook alerts still being sent for disabled metrics

**To Reproduce**
1. Disable alert for metric

<img width="1910" height="288" alt="Image" src="https://github.com/user-attachments/assets/f65d215b-f1b3-4af7-95d3-fc53cc2a27e7" />

3. Increase usage on metric above global default threshold
4. Get webhook alert

<img width="813" height="331" alt="Image" src="https://github.com/user-attachments/assets/da309791-1c7c-4eed-bc43-79aebb495d7e" />

**Expected behavior**
No alert for disabled metrics

**Environment:**
 - Pulse Version: 4.23.0
 - Installation Type: ProxmoxVE LXC

**Comment by rcourtman** [comment]
Update: Disabled metrics now clear pending notifications so webhooks stop firing. Commit c6c0ac63e.

**Comment by revilo951** [comment]
Just wondering if this fix is planned to be released some time soon?

And thanks for an amazing bit of software! 😄

**Comment by rcourtman** [comment]
Already released in v4.24.0 and v4.25.0. Upgrade to get the fix.

**Comment by revilo951** [comment]
Deleted last comment, I am still seeing an issue where higher thresholds than the global are triggering notifications (which I tried to stop the notifications with this bug). I'll double check.

**Comment by revilo951** [comment]
Looks like it's still occurring:

<img width="3040" height="1055" alt="Image" src="https://github.com/user-attachments/assets/0bb37696-b728-481a-a7bb-62e359cbb8e7" />

Edit: I am an idiot. Disregard this. I will continue testing.

**Comment by revilo951** [comment]
OK, I'm not going mad after all, it's still happening. 

I have noticed that when the page loads, the disabled metric briefly shows "80%" before flicking back to "Off", not sure if that's contributing?

<img width="3084" height="1288" alt="Image" src="https://github.com/user-attachments/assets/50362ab7-bc7b-49b6-a894-b4fe032fd289" />

**Comment by rcourtman** [comment]
Need your Pulse version. Disabled-metric webhook issue is fixed in v4.24.0 and v4.25.0. Migration resets on custom thresholds are addressed by commit 4ae426c8f but that fix has not shipped in a release yet. If you are running a release build, thresholds will still revert after a VM migration until the next release is out; building from main now will include the change. Confirm whether a migration happened before the notification and include the metric name, alert payload, and service logs for that timestamp if you are already on v4.24.0 or newer.

**Comment by revilo951** [comment]
Version: 4.25.0

No migrations occuring.

Metric name is `frigate`

Payload:
```
Pulse Alert: Warning
Storage at 89.3%
Resource frigate
Node cluster
Type Usage
Value 89.3%
Threshold 80%
Duration 9m
Pulse Monitoring•Today at 07:14
```

Is this what you need for the service logs?
[pulse-diagnostics-sanitized-2025-11-06.json](https://github.com/user-attachments/files/23401887/pulse-diagnostics-sanitized-2025-11-06.json)

**Comment by rcourtman** [comment]
The Oct 16 commit (c6c0ac63e) that shipped in v4.24.0 only clears alerts when a per-resource override disables a metric. With a DisableAll* flag, the Check* path bails out before cleanup, so those alerts sit in `m.activeAlerts` and the webhook loop keeps sending them. I pushed a patch that makes `reevaluateActiveAlertsLocked` honor every DisableAll flag and resolves the matching alerts, and the Check* methods now drop them before returning when a global disable is active. Added regression coverage for the storage toggle. Pull current main (it ships in the next point release) and the webhook spam stops once the flag flips.

**Comment by revilo951** [comment]
Fixed! Awesome work, thanks @rcourtman :)

**Comment by revilo951** [comment]
There seems to have been a regression, this issue is back after the latest release?

**Comment by rqbanerjee** [comment]
I am seeing this issue on 4.32.3 today after upgrading.
A docker image that easily exceeds the memory threshold of 80% is qbittorrentvpn when downloading large Linux ISOs ([known issue](https://github.com/qbittorrent/qBittorrent/issues/18302) for that container)

Steps to reproduce the behavior:
1. Go to 'Alerts -> Thresholds
2. Add 'qbittorrent' to ignored container prefixes, then a newline. Save.
3. On the same page, under Containers, set "MEMORY WARN %" to 0, to disable the memory alert
4. On the same page, under Containers, turn off alerts with the toggle button for qbittorrent, to disable all alerts for the container
5. Wait 5-10 minutes and receive the alert via webhook. I have my webhook alert going to signal-api container to send a message to signal messenger

**Comment by devachnid** [comment]
Issue still present in v4.36.2

**Comment by rcourtman** [comment]
Thanks for the report. Can you share a bit more detail to help narrow this down?

1. **Pulse version** - the exact version number from Settings or the API (\`curl http://localhost:7655/api/version\`)
2. **How did you disable the alert?** - Did you set the threshold to 0 (or -1), toggle the container off, or add it to ignored prefixes?
3. **Timing** - Did the alert fire immediately after saving, or on the next webhook check (which happens every 30s)?
4. **Container type** - Is this alerting for a Docker container, Proxmox LXC, or something else?

v5 (RC available now) significantly reworked alerts and thresholds. If you're able to test 5.0.0-rc.1, that would help confirm whether this is fixed there. The install is non-destructive - your data persists.

In the meantime, a workaround that should definitely work: go to **Alerts → Thresholds** and toggle the master switch for that container type (e.g., "CONTAINERS" toggle under Docker section) off entirely. That bypasses the per-metric logic that seems to be misbehaving.

**Comment by rcourtman** [comment]
[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)
