### ISSUE TITLE
Disable password login

### ISSUE THREAD

**Issue by thelan** [rcourtman/Pulse#750]
Hello,

I think it should be handy to have an option to disable password login.

For instance i'm using OIDC SSO for auth and would like to hide the "username / password" form from the login page to avoid users confusion.

**Comment by rcourtman** [comment]
Implemented in commit 6b84b9a2.

Added a new environment variable `PULSE_AUTH_HIDE_LOCAL_LOGIN=true` that hides the username/password form from the login page when you're using OIDC SSO.

**How to use:**
Add this to your `.env` file:
```bash
PULSE_AUTH_HIDE_LOCAL_LOGIN=true
```

This will hide the local login form, showing only the "Continue with Single Sign-On" button.

**Safety feature:** If you ever need to access the local login form (e.g., if OIDC is down), you can add `?show_local=true` to the URL:
```
https://your-pulse-instance/login?show_local=true
```

This approach avoids the security and upgrade issues that led to `DISABLE_AUTH` being removed, while solving your UX concern about user confusion.

**Comment by thelan** [comment]
😱 That was fast edit.

Actually that sounds find to me.

Thank-you your awesome :)

**Comment by thelan** [comment]
Maybe you should also hide the title ?

<img width="646" height="510" alt="Image" src="https://github.com/user-attachments/assets/a0eb9224-56b2-4ee5-9624-b0699e3e324f" />

**Comment by BatisteDONDOGLIO** [comment]
> **Safety feature:** If you ever need to access the local login form (e.g., if OIDC is down), you can add `?show_local=true` to the URL:
> 
> ```
> https://your-pulse-instance/login?show_local=true
> ```
> 
> This approach avoids the security and upgrade issues that led to `DISABLE_AUTH` being removed, while solving your UX concern about user confusion.  

I think you meant ```https://your-pulse-instance/?show_local=true``` ? Because ```/login?show_local=true``` results in a blank page for me. But ```/?show_local=true``` works as expected.

And I also agree with this:
> Maybe you should also hide the title ?
> <img alt="Image" width="646" height="510" src="https://private-user-images.githubusercontent.com/714814/518370146-a0eb9224-56b2-4ee5-9624-b0699e3e324f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQyNTE5NjMsIm5iZiI6MTc2NDI1MTY2MywicGF0aCI6Ii83MTQ4MTQvNTE4MzcwMTQ2LWEwZWI5MjI0LTU2YjItNGVlNS05NjI0LWIwNjk5ZTNlMzI0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyN1QxMzU0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmIxN2Y4NmUzYmZmYTZlNjI0NTEyMDhiMTNhZjI0ODdlOWU2ZTExNDZhOGZkYjkwMzhmZGU5MmRlZWYxZWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.csTTtf_D44sVC_ngL77A-RANsp4BiPoOctLNfQy3QLs">

Thanks tho! This is very useful.

**Comment by rcourtman** [comment]
Both points addressed in commit 22dac34a:

1. **URL path**: Fixed the documentation in `docs/OIDC.md` - the correct URL is `/?show_local=true` (not `/login?show_local=true` since there's no `/login` route in this SPA)

2. **Subtitle**: The "Enter your credentials to continue" subtitle is now hidden when local login is hidden, since it doesn't make sense when there's no credential form

The "Welcome to Pulse" title remains visible since it's generic and still appropriate for the SSO flow.

Will be in the next release.

**Comment by BatisteDONDOGLIO** [comment]
Thanks, @rcourtman 

However, it doesn't seem to be working correctly. On build 4.34.0, the behavior is as follows:

The toggleable switch "Hide local login form" under Settings > Security > Authentication does not seem to stick and isn't being applied correctly, as the login form is still showing. Simply enabling and refreshing the page will result in it being toggled off again.

Manually setting
```json
"hideLocalLogin":true
```
in ```system.json``` makes the toggle switch to the correct state, visually speaking, however, the login form still isn't hidden.

It seems only setting the environment variable ```PULSE_AUTH_HIDE_LOCAL_LOGIN=true``` hides the login form, but the message "Or use your admin credentials to sign in below" is still showing in this case.

**Comment by rcourtman** [comment]
Fixed in commit 8afc4d0c.

The issues were:
1. The backend `HandleUpdateSystemSettings()` wasn't processing the `hideLocalLogin` field, so toggle changes weren't saved
2. The "or" divider and "Use your admin credentials" message weren't conditionally hidden when local login is hidden

Both are now fixed. Will be in the next release.

**Comment by thelan** [comment]
Seems fine to me now
