### ISSUE TITLE
Unable to install Unified Agent

### ISSUE THREAD

**Issue by malkinskir** [rcourtman/Pulse#760]
**Describe the bug**

**To Reproduce**
1. Run `curl -fsSL http://192.168.0.181:7655/install.sh` (replace IP with your server IP) on host that you want install agent OR open http://192.168.0.181:7655/install.sh
2. Command returns `curl: (22) The requested URL returned error: 404`
3. URL returns: `Install script not found`

**Expected behavior**
install.sh script should be downloaded. 

**Environment:**
 - Pulse Version: [e.g. v4.33.0]
 - Installation Type: [Manual on debian 13 LXC]

**Additional context**
For comparison http://192.168.0.181:7655/install-docker-agent.sh works fine and downloads the script. 

💡 **Tip:** If you're experiencing connection issues, API errors, or missing data, you can attach diagnostics from Settings → Diagnostics tab → Export for GitHub (sanitized version)

**Comment by malkinskir** [comment]
[pulse-diagnostics-sanitized-2025-11-26.json](https://github.com/user-attachments/files/23778195/pulse-diagnostics-sanitized-2025-11-26.json)

**Comment by ryansully** [comment]
Might be related to https://github.com/rcourtman/Pulse/issues/751?

To reiterate here, the issue for me wasn't with the install script not being found, but with the agent itself: `/download/pulse-agent`.

**Comment by resal1510** [comment]
Same error for me. Latest Pulse version in LXC (installed from the one-liner of the QuickStart section + updated from the web GUI).

[pulse-diagnostics-sanitized-2025-11-26.json](https://github.com/user-attachments/files/23779153/pulse-diagnostics-sanitized-2025-11-26.json)

**Comment by rcourtman** [comment]
Can you provide more details to help debug this?

1. What version of Pulse is actually running? Run:
   ```
   /opt/pulse/bin/pulse --version
   ```

2. What's in the scripts directory?
   ```
   ls -la /opt/pulse/scripts/
   ```

3. Did you upgrade from an older version, or is this a fresh install?

---

The `/install.sh` endpoint serves the unified agent installer from `/opt/pulse/scripts/install.sh`. This file should have been deployed during installation.

**Workaround**: Re-run the installer to deploy the missing scripts:
```bash
curl -fsSL https://github.com/rcourtman/Pulse/releases/latest/download/install.sh | sudo bash
```

This will update to the latest version and deploy all agent scripts including `install.sh`.

---

For context: The unified agent feature was added in v4.33.0. The deployment function should copy `scripts/install.sh` from the release tarball to `/opt/pulse/scripts/install.sh`. If you upgraded from v4.32.x, the scripts should have been deployed during the upgrade.

**Comment by rcourtman** [comment]
Fixed in commit 60f85693.

**Root cause**: The installer was missing:
1. `copy_unified_agent_binaries_from_dir()` function to deploy `pulse-agent-*` binaries from the tarball
2. `install.sh` and `install.ps1` in the `deploy_agent_scripts()` array

**Workaround (until next release)**: Re-run the installer:
```bash
curl -fsSL https://github.com/rcourtman/Pulse/releases/latest/download/install.sh | sudo bash
```

This downloads the latest install.sh from main which now includes the fix.

**Comment by rcourtman** [comment]
**Correction**: The workaround above won't work immediately because GitHub releases serve the install.sh from the v4.33.0 release, not from main.

**Alternative workaround**: Download the updated install.sh directly from main:
```bash
curl -fsSL https://raw.githubusercontent.com/rcourtman/Pulse/main/install.sh | sudo bash
```

Or manually deploy the scripts:
```bash
cd /tmp
curl -sL https://github.com/rcourtman/Pulse/releases/download/v4.33.0/pulse-v4.33.0-linux-amd64.tar.gz | tar xzf -
sudo mkdir -p /opt/pulse/scripts /opt/pulse/bin
sudo cp scripts/install.sh scripts/install.ps1 /opt/pulse/scripts/
sudo cp bin/pulse-agent-* /opt/pulse/bin/
sudo chown -R pulse:pulse /opt/pulse/scripts /opt/pulse/bin
```

**Comment by krestaino** [comment]
> **Correction**: The workaround above won't work immediately because GitHub releases serve the install.sh from the v4.33.0 release, not from main.
> 
> **Alternative workaround**: Download the updated install.sh directly from main:
> 
> curl -fsSL https://raw.githubusercontent.com/rcourtman/Pulse/main/install.sh | sudo bash
> 
> Or manually deploy the scripts:
> 
> cd /tmp
> curl -sL https://github.com/rcourtman/Pulse/releases/download/v4.33.0/pulse-v4.33.0-linux-amd64.tar.gz | tar xzf -
> sudo mkdir -p /opt/pulse/scripts /opt/pulse/bin
> sudo cp scripts/install.sh scripts/install.ps1 /opt/pulse/scripts/
> sudo cp bin/pulse-agent-* /opt/pulse/bin/
> sudo chown -R pulse:pulse /opt/pulse/scripts /opt/pulse/bin

Was running into the same issue. Can confirm this fixed it.

**Comment by malkinskir** [comment]
I have updated to 4.33.1, but still unable to run `install.sh` for unified agent
Getting same error
```
[adguard-home-222][admin-ssh][6:14][0] ~   curl -fsSL http://192.168.0.181:7655/install.sh
curl: (22) The requested URL returned error: 404
```


Here's output from Pulse host. Just to add I'm upgrading from older version using webui "Upgrade Now" button. Not using fresh install
```
[pulse][admin-ssh][6:12][0] ~  /opt/pulse/bin/pulse --version
pulse version v4.33.1
[pulse][admin-ssh][6:12][0] ~  ls -la /opt/pulse/scripts/    
total 244
drwxr-xr-x 2 pulse pulse  4096 Nov 10 17:03 .
drwxr-xr-x 5 pulse pulse  4096 Nov 10 17:08 ..
-rwxr-xr-x 1 pulse pulse 24663 Nov 11 08:38 install-container-agent.sh
-rwxr-xr-x 1 pulse pulse 53943 Nov 11 08:38 install-docker-agent.sh
-rwxr-xr-x 1 pulse pulse 28088 Nov 11 08:38 install-docker.sh
-rwxr-xr-x 1 pulse pulse 15264 Nov 11 08:38 install-host-agent.ps1
-rwxr-xr-x 1 pulse pulse 33737 Nov 11 08:38 install-host-agent.sh
-rwxr-xr-x 1 pulse pulse 56517 Nov 11 08:38 install-sensor-proxy.sh
-rwxr-xr-x 1 pulse pulse  4926 Nov 11 08:38 uninstall-host-agent.ps1
-rwxr-xr-x 1 pulse pulse  6100 Nov 11 08:38 uninstall-host-agent.sh
[pulse][admin-ssh][6:12][0]
```

**Comment by rcourtman** [comment]
The v4.33.1 installer should deploy `install.sh` to `/opt/pulse/scripts/`, but based on your output the scripts directory hasn't been updated since Nov 10-11.

Could you check if there's an update log that shows what happened?
```bash
ls -la /var/log/pulse/update-*.log
cat /var/log/pulse/update-*.log | tail -100
```

In the meantime, the manual workaround should deploy the missing scripts:
```bash
curl -fsSL https://raw.githubusercontent.com/rcourtman/Pulse/main/install.sh | sudo bash
```

Or manually copy from the release tarball:
```bash
cd /tmp
curl -sL https://github.com/rcourtman/Pulse/releases/download/v4.33.1/pulse-v4.33.1-linux-amd64.tar.gz | tar xzf -
sudo cp scripts/install.sh scripts/install.ps1 /opt/pulse/scripts/
sudo chown pulse:pulse /opt/pulse/scripts/install.sh /opt/pulse/scripts/install.ps1
sudo chmod 755 /opt/pulse/scripts/install.sh /opt/pulse/scripts/install.ps1
```

**Comment by rcourtman** [comment]
Fix pushed in 6ff5ae42 - web UI upgrades now deploy agent scripts and binaries to `/opt/pulse/scripts/` and `/opt/pulse/bin/`, not just the main binary.

This will be in the next release. In the meantime, the manual workaround in my previous comment should work.

**Comment by lruckman** [comment]
> Fix pushed in [6ff5ae4](https://github.com/rcourtman/Pulse/commit/6ff5ae4200c9fad25b7aca4956c1fb869d54d5cb) - web UI upgrades now deploy agent scripts and binaries to `/opt/pulse/scripts/` and `/opt/pulse/bin/`, not just the main binary.
> 
> This will be in the next release. In the meantime, the manual workaround in my previous comment should work.

I've tried the manual workaround and at least in my case it fails to do the `sudo chown pulse:pulse ...` line complaining that it doesn't know a user pulse.

**Comment by rcourtman** [comment]
If there's no `pulse` user (e.g., Docker installations or custom setups), you can skip the chown step or use root:

```bash
cd /tmp
curl -sL https://github.com/rcourtman/Pulse/releases/download/v4.33.1/pulse-v4.33.1-linux-amd64.tar.gz | tar xzf -
sudo cp scripts/install.sh scripts/install.ps1 /opt/pulse/scripts/
sudo chmod 755 /opt/pulse/scripts/install.sh /opt/pulse/scripts/install.ps1
```

Or if your setup uses a different user, check what owns `/opt/pulse` and use that:
```bash
ls -la /opt/pulse
# Then use that user/group in the chown command
```

**Comment by malkinskir** [comment]
I'm still struggling to install unified agent on one of my hosts. It's able to pull `install.sh` file but then fails on `download/pulse-agent?arch=linux-amd64...`
I have added some output from my host below. Just to add I have updated to latest v4.34.0 recently using web interface. `install.sh` script was manually imported using manual workaround above. Noticed I don't  have any logs for update in log folder. I'm thinking I'll just do clean install again as I'm using Pulse for couple weeks only. I love the product btw!

```
[adguard-home-222][admin-ssh][8:26][0] ~  curl -fsSL http://192.168.0.181:7655/install.sh | sudo bash -s -- --url http://192.168.0.181:7655 --token 35da9*************************7fc701 --interval 30s
[INFO] Downloading agent from http://192.168.0.181:7655/download/pulse-agent?arch=linux-amd64...
curl: (22) The requested URL returned error: 404
[ERROR] Download failed. Check URL and connectivity.
Press Enter to exit..
```


```
[pulse][admin-ssh][8:31][0] ~  /opt/pulse/bin/pulse --version
pulse version v4.34.0
[pulse][admin-ssh][8:31][0] ~  ls -la /opt/pulse/scripts/    
total 276
drwxr-xr-x 2 pulse pulse  4096 Nov 27 18:19 .
drwxr-xr-x 5 pulse pulse  4096 Nov 10 17:08 ..
-rwxr-xr-x 1 pulse pulse 24663 Nov 11 08:38 install-container-agent.sh
-rwxr-xr-x 1 pulse pulse 53943 Nov 11 08:38 install-docker-agent.sh
-rwxr-xr-x 1 pulse pulse 28088 Nov 11 08:38 install-docker.sh
-rwxr-xr-x 1 pulse pulse 15264 Nov 11 08:38 install-host-agent.ps1
-rwxr-xr-x 1 pulse pulse 33737 Nov 11 08:38 install-host-agent.sh
-rwxr-xr-x 1 pulse pulse 56517 Nov 11 08:38 install-sensor-proxy.sh
-rwxr-xr-x 1 pulse pulse 10161 Nov 27 18:21 install.ps1
-rwxr-xr-x 1 pulse pulse 18714 Nov 27 18:21 install.sh
-rwxr-xr-x 1 pulse pulse  4926 Nov 11 08:38 uninstall-host-agent.ps1
-rwxr-xr-x 1 pulse pulse  6100 Nov 11 08:38 uninstall-host-agent.sh
[pulse][admin-ssh][8:31][0] ~  ls -la /opt/pulse             
total 28472
drwxr-xr-x 5 pulse pulse    4096 Nov 10 17:08 .
drwxr-xr-x 3 root  root     4096 Nov 10 17:03 ..
drwx------ 2 pulse pulse    4096 Nov 10 17:08 .ssh
-rw-r--r-- 1 pulse pulse       7 Nov 28 08:25 VERSION
drwxr-xr-x 2 pulse pulse    4096 Nov 28 08:25 bin
-rwxr-xr-x 1 pulse pulse 7446712 Nov 11 08:38 pulse-docker-agent
-rwxr-xr-x 1 pulse pulse 7446712 Nov 10 17:03 pulse-docker-agent-linux-amd64
-rwxr-xr-x 1 pulse pulse 7012536 Nov 10 17:03 pulse-docker-agent-linux-arm64
-rwxr-xr-x 1 pulse pulse 7209144 Nov 10 17:03 pulse-docker-agent-linux-armv7
drwxr-xr-x 2 pulse pulse    4096 Nov 27 18:19 scripts
[pulse][admin-ssh][8:31][0] ~  ls -la /var/log/pulse/        

total 11280
drwxr-xr-x 2 root root     4096 Nov 17 17:11 .
drwxr-xr-x 8 root root     4096 Nov 28 08:29 ..
-rw-r--r-- 1 root root 11535523 Nov 28 08:31 host-agent.log
[pulse][admin-ssh][8:31][0] ~  
```

**Comment by rcourtman** [comment]
The new error you're seeing (`/download/pulse-agent` returning 404) is because the unified agent binaries aren't in `/opt/pulse/bin/`. This is the same underlying issue - web UI upgrades weren't deploying all the agent files.

The fix (commit 6ff5ae42) is already in main but not yet released. In the meantime:

```bash
cd /tmp
curl -sL https://github.com/rcourtman/Pulse/releases/download/v4.34.0/pulse-v4.34.0-linux-amd64.tar.gz | tar xzf -
sudo cp bin/pulse-agent-* /opt/pulse/bin/
sudo chown pulse:pulse /opt/pulse/bin/pulse-agent-*
sudo chmod 755 /opt/pulse/bin/pulse-agent-*
```

This will deploy the missing unified agent binaries. The fix will be included in the next release so this won't happen on future upgrades.

**Comment by malkinskir** [comment]
I was able to install agent after copying files across using command above. Thanks for the support!
```
[adguard-home-222][admin-ssh][10:34][0] ~  curl -fsSL http://192.168.0.181:7655/install.sh | sudo bash -s -- --url http://192.168.0.181:7655 --token 322**************3e683 --interval 30s
[INFO] Downloading agent from http://192.168.0.181:7655/download/pulse-agent?arch=linux-amd64...
[INFO] Installing binary to /usr/local/bin/pulse-agent...
[INFO] Checking for legacy agents...
[WARN] Removing legacy pulse-host-agent...
^@[INFO] Configuring Systemd service at /etc/systemd/system/pulse-agent.service...
Created symlink '/etc/systemd/system/multi-user.target.wants/pulse-agent.service' -> '/etc/systemd/system/pulse-agent.service'.
[INFO] Service started.
[adguard-home-222][admin-ssh][10:36][0] ~ 
```

**Comment by rcourtman** [comment]
Closing as fixed. The underlying issue (web UI upgrades not deploying agent scripts/binaries) was fixed in commits 60f85693 and 6ff5ae42. The fix is in main and will be included in the next release.

Users who upgraded via the web UI can use the manual workaround to deploy the missing files:
```bash
cd /tmp
curl -sL https://github.com/rcourtman/Pulse/releases/download/v4.34.0/pulse-v4.34.0-linux-amd64.tar.gz | tar xzf -
sudo cp scripts/install.sh scripts/install.ps1 /opt/pulse/scripts/
sudo cp bin/pulse-agent-* /opt/pulse/bin/
sudo chmod 755 /opt/pulse/scripts/install.sh /opt/pulse/scripts/install.ps1 /opt/pulse/bin/pulse-agent-*
```
