### ISSUE TITLE
Agent service not created in Windows

### ISSUE THREAD

**Issue by byTute1976** [rcourtman/Pulse#776]
<img width="1814" height="555" alt="Image" src="https://github.com/user-attachments/assets/561de197-3c21-4911-842d-47487020002f" />

**Comment by byTute1976** [comment]
He revisado el script de PowerShell y se executa "SC CREATE" con parametros incorrectos y da error, pero no se ve en la captura por que se omite la salida.

**Comment by rcourtman** [comment]
Thanks for reporting this and for investigating the PowerShell script.

You're correct - the `SC CREATE` command had incorrect parameter handling. The `binPath` value wasn't properly quoted, so when it contained embedded quotes and spaces (the exe path plus arguments), SC.EXE parsed it incorrectly.

Fixed in 5a43ab4e - will be in the next release.

If you need to test before then, you can manually edit line 318 in `install.ps1` to add quotes around `$BinPath`:
```powershell
$scOutput = sc.exe create $AgentName binPath= "$BinPath" start= auto ...
```

**Comment by jwillo** [comment]
Can I recommend that you use the Poweshell native (not CMD shell) to create the service, I am up to date and still having problems creating the service, the line would look like I did it manually and created the service
`New-Service -Name "PulseAgent" -BinaryPathName "C:\Program Files\Pulse\pulse-agent.exe" -StartupType Automatic -DisplayName "Pulse Agent Service" -Description "Pulse monitoring agent service"`
so with the variables
`$scOutput = New-Service -Name $AgentName -BinaryPathName $BinPath -StartupType Automatic`

**Comment by rcourtman** [comment]
The installer now uses `New-Service` instead of `sc.exe` (commit 1109395). This was applied to `scripts/install.ps1` after your report.

If you're still hitting issues, you may be using a cached installer. Try downloading fresh:
```powershell
irm https://raw.githubusercontent.com/rcourtman/Pulse/main/scripts/install.ps1 | iex
```

Let me know if you still encounter problems with the updated script.

**Comment by rcourtman** [comment]
Fixed in commit 1109395 - Windows installer now uses New-Service instead of sc.exe.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)
