### ISSUE TITLE
Problem with installing the agent - Agent Type "Host" not active/shown

### ISSUE THREAD

**Issue by morskipas** [rcourtman/Pulse#778]
Hello everyone,
I found this project a few days ago and am very impressed. Thank you very much for your efforts and good work.

I added my first hosts and Docker a few days ago (I think it was v4.32.7) and there were no problems at all, everything was recognized immediately. 
Yesterday, I wanted to add a few more hosts/docker (v4.33.1) and noticed that after installing the agent including the Docker option, the host is not always added, but the docker containers are always recognized. In fact, when I go to Settings / Agents, the type of the newly added hosts changes every few seconds, sometimes showing Host & Docker, sometimes only Docker. The Docker is always listed as the type.
What could be the cause? I have currently added about 20 hosts, all of them work fine except for the last 3 or 4 I added. I have a Proxmox environment with about 20 LXC containers and Docker containers contained inside them. All LXCs are the same, Ubuntu 24.04 and Docker 29.1.1. Today I also updated to puls 4.34.0, but even after reinstalling the agent, the result is the same.

Here are two screenshots showing the type changing every few seconds, but only for the newly added hosts.

<img width="1974" height="1252" alt="Image" src="https://github.com/user-attachments/assets/61585cfa-ed03-46e4-a6dd-8e181866edb8" />

<img width="1818" height="675" alt="Image" src="https://github.com/user-attachments/assets/1cad2e5b-fb6c-498a-a346-1a754e801003" />

I would be grateful for any help.

**Comment by rcourtman** [comment]
Thanks for the report. This looks like a timing issue in how the UI merges host and docker agent data.

When a unified agent reports, it sends separate host and docker reports. Each triggers an independent state broadcast to the UI. The Settings/Agents page merges these two data sources by hostname - if a broadcast arrives where only the docker agent data has been updated (host data not yet in that snapshot), the UI briefly shows just "Docker" type.

I'll work on a fix to stabilize the type display. In the meantime, the actual monitoring should be working correctly - this is primarily a visual flapping issue on the Agents settings page.

**Comment by morskipas** [comment]
> Thanks for the report. This looks like a timing issue in how the UI merges host and docker agent data.
> 
> When a unified agent reports, it sends separate host and docker reports. Each triggers an independent state broadcast to the UI. The Settings/Agents page merges these two data sources by hostname - if a broadcast arrives where only the docker agent data has been updated (host data not yet in that snapshot), the UI briefly shows just "Docker" type.
> 
> I'll work on a fix to stabilize the type display. In the meantime, the actual monitoring should be working correctly - this is primarily a visual flapping issue on the Agents settings page.

Super ... Thanks a lot!

**Comment by rcourtman** [comment]
Fixed in commit 67519304.

**Root cause**: The WebSocket handler was calling `setState` separately for `dockerHosts` and `hosts`. When a unified agent reports both, the UI's `allHosts` memo recalculates twice - first seeing only updated dockerHosts (showing "Docker"), then seeing both (showing "Host & Docker").

**Fix**: Batch both updates into a single atomic `setState` call using `produce()` when both are present in the same message.

This will be in the next release. Thanks for the report!

**Comment by roelbeun** [comment]
I actually have it visa-versa, host shows but not the docker info. Is this related or worth another Issue report? @rcourtman 

> Dec 01 09:12:46 <hostname_redacted> systemd[1]: Started pulse-agent.service - Pulse Unified Agent.
> Dec 01 09:12:46 <hostname_redacted>  pulse-agent[3482682]: {"level":"info","version":"v4.34.1","pulse_url":"http://localhost:7655","host_agent":true,"docker_agent":true,"auto_update":true,"time":"202>
> Dec 01 09:12:46 <hostname_redacted>  pulse-agent[3482682]: {"level":"info","time":"2025-12-01T09:12:46+01:00","message":"Host agent module started"}
> Dec 01 09:12:46 <hostname_redacted>  pulse-agent[3482682]: {"level":"info","component":"pulse-docker-agent","runtime":"docker","daemon_host":"unix:///var/run/docker.sock","version":"27.3.1","time":"2>
> Dec 01 09:12:46 <hostname_redacted>  pulse-agent[3482682]: {"level":"info","time":"2025-12-01T09:12:46+01:00","message":"Docker agent module started"}
> Dec 01 09:12:47 <hostname_redacted>  pulse-agent[3482682]: {"level":"warn","component":"pulse-docker-agent","hostID":"<hostID_redacted> ","pulseURL":"http://localhost:7655","detail">
> lines 1-16/16 (END)

**Comment by rcourtman** [comment]
@Ruvetuve That's a separate issue. Your logs show:

```
{"level":"warn","component":"pulse-docker-agent","hostID":"...","pulseURL":"http://localhost:7655","detail":...
```

This is the "host was previously removed" warning - Pulse is rejecting docker reports from this agent because the host was deleted at some point.

To fix: Go to **Settings → Docker → Removed hosts** and click **Allow re-enroll** for this host. The agent should start reporting again within one report interval (default 30s).

Alternatively, rerun the installer with a `docker:manage` token to clear the block automatically.

**Comment by roelbeun** [comment]
Oke there is no _Settings_ > _Docker_ anymore, only _Proxmox_ and _Agents_

Ive created a new scope for docker manage, then install the agent. 

Then generated a normal API token for host+docker and installed these over the old installation, i still get:

> docker host .. was removed at 2025-12-01T09:02:47+01:00 and cannot report again. Use Allow re-enroll in Settings -> Docker -> Removed hosts or rerun the installer with a docker:manage token to clear this block"

**Comment by morskipas** [comment]
@rcourtman -  Just a quick note: unfortunately, I'm still experiencing the issue with v4.35.

<img width="1163" height="352" alt="Image" src="https://github.com/user-attachments/assets/ef1bc58a-078c-428a-a91c-b1e4f4c515c8" />

<img width="1135" height="408" alt="Image" src="https://github.com/user-attachments/assets/027456a2-14da-42d1-8120-71938c3b4e05" />

And if I go to hosts, the affected hosts are not shown (only every few seconds)

<img width="1338" height="458" alt="Image" src="https://github.com/user-attachments/assets/e0ce6789-8155-45b4-b320-cccaeba148ff" />

**Comment by rcourtman** [comment]
@morskipas The initial fix (67519304) addressed batching WebSocket updates but didn't fully solve the problem. A second fix (6c1a0815) was committed after v4.35.0 was released, adding transient empty payload protection for hosts data.

This will be in the next release. The flapping should stop once you upgrade.

@Ruvetuve The error message was outdated. The correct path is **Settings → Agents**, then scroll down to the **Removed Docker Hosts** section at the bottom. If you have removed hosts, you'll see them listed there with an "Allow re-enroll" button.

I've pushed a fix (46a72a76) to update the error message to show the correct path.

For your specific issue: the host was previously removed (either manually or via token conflict), and Pulse is now rejecting reports from that agent. Go to Settings → Agents → Removed Docker Hosts and click "Allow re-enroll" for that host.

**Comment by morskipas** [comment]
> [@morskipas](https://github.com/morskipas) The initial fix ([6751930](https://github.com/rcourtman/Pulse/commit/67519304f988f304f3deefa6904e8e95e7f598d5)) addressed batching WebSocket updates but didn't fully solve the problem. A second fix ([6c1a081](https://github.com/rcourtman/Pulse/commit/6c1a0815ea0d28b10ffa12f70cdd1124fb324963)) was committed after v4.35.0 was released, adding transient empty payload protection for hosts data.
> 
> This will be in the next release. The flapping should stop once you upgrade.
> 
> [@Ruvetuve](https://github.com/Ruvetuve) The error message was outdated. The correct path is **Settings → Agents**, then scroll down to the **Removed Docker Hosts** section at the bottom. If you have removed hosts, you'll see them listed there with an "Allow re-enroll" button.
> 
> I've pushed a fix ([46a72a7](https://github.com/rcourtman/Pulse/commit/46a72a7600e905ca22e59b7050aead6d0ba17be8)) to update the error message to show the correct path.
> 
> For your specific issue: the host was previously removed (either manually or via token conflict), and Pulse is now rejecting reports from that agent. Go to Settings → Agents → Removed Docker Hosts and click "Allow re-enroll" for that host.

@rcourtman - Thank you very much for your answer

**Comment by roelbeun** [comment]
> [@morskipas](https://github.com/morskipas) The initial fix ([6751930](https://github.com/rcourtman/Pulse/commit/67519304f988f304f3deefa6904e8e95e7f598d5)) addressed batching WebSocket updates but didn't fully solve the problem. A second fix ([6c1a081](https://github.com/rcourtman/Pulse/commit/6c1a0815ea0d28b10ffa12f70cdd1124fb324963)) was committed after v4.35.0 was released, adding transient empty payload protection for hosts data.
> 
> This will be in the next release. The flapping should stop once you upgrade.
> 
> [@Ruvetuve](https://github.com/Ruvetuve) The error message was outdated. The correct path is **Settings → Agents**, then scroll down to the **Removed Docker Hosts** section at the bottom. If you have removed hosts, you'll see them listed there with an "Allow re-enroll" button.
> 
> I've pushed a fix ([46a72a7](https://github.com/rcourtman/Pulse/commit/46a72a7600e905ca22e59b7050aead6d0ba17be8)) to update the error message to show the correct path.
> 
> For your specific issue: the host was previously removed (either manually or via token conflict), and Pulse is now rejecting reports from that agent. Go to Settings → Agents → Removed Docker Hosts and click "Allow re-enroll" for that host.

Sorry to say, there is no Removed Docker Hosts section .. might be because ive also removed the agent from the Managed Agent screen?

Maybe its now in limbo?

Edit: the host is now suddenly visible in Host tab + Docker! no clue how that happend.

**Comment by morskipas** [comment]
@rcourtman 
I am currently on version 4.36.2. The problem has shifted somewhat; under Settings/Agents, the order in the Type column for the affected hosts changes. Sometimes it is Host / Docker, sometimes Docker / Host, but sometimes it is still just Docker.

<img width="958" height="754" alt="Image" src="https://github.com/user-attachments/assets/b7ddc0b5-dbc0-4519-9760-03ba6af70c46" />

When I go to Hosts, the affected hosts are only visible from time to time. For me, for example, it's the hosts dhcp-01, dhcp-02, ca and netbird. Sometimes they're there, sometimes they're not.

In the next picture you can see, that dhcp-01 an ca is missing.

<img width="1035" height="445" alt="Image" src="https://github.com/user-attachments/assets/89a0b50d-7583-403f-9ee2-074e5f0c60d6" />

**Comment by rcourtman** [comment]
Multiple fixes for agent identity and host flapping were shipped in v5. If you're still experiencing this on v5.x, please reopen with details.

[How Pulse handles triage](https://github.com/rcourtman/Pulse/blob/main/docs/AI_TRANSPARENCY.md)

**Comment by morskipas** [comment]
> Multiple fixes for agent identity and host flapping were shipped in v5. If you're still experiencing this on v5.x, please reopen with details.
> 
> _Closed by automated triage. Feel free to reopen if this needs further attention._

@rcourtman - Perfect, just installed v5 rc4. The problem is gone, thank you very much for this great project :-)
